version: '3.8'

services:
  user-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-simulator-playwright:latest
    environment:
      # Delay configuration
      - MIN_DELAY=2000            # Minimum delay in milliseconds
      - MAX_DELAY=10000           # Maximum delay in milliseconds

      # Concurrency settings
      - CONCURRENCY=5             # Number of concurrent sessions per script instance
      - PM2_INSTANCES=3           # Number of script instances to run

      # Target website
      - TARGET_WEBSITE=https://www.example.com

      # Resource optimization
      - DISABLE_IMAGES=true       # Disable images to reduce resource usage
      - DISABLE_CSS=true          # Disable CSS to reduce resource usage

      # Viewport settings
      - VIEWPORT_WIDTH=1024       # Width of the browser viewport
      - VIEWPORT_HEIGHT=768       # Height of the browser viewport

      # Navigation options
      - ONLY_INTERNAL_LINKS=true  # Set to 'true' to only follow internal links

      # Custom headers
      - CUSTOM_HEADERS={"X-Custom-Header1":"Value1","X-Custom-Header2":"Value2"}  # JSON string of custom headers

      # Debug mode
      - DEBUG=true                # Set to 'true' to enable debug logging

      # User-Agent string
      - USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

      # Navigation timeout
      - NAVIGATION_TIMEOUT=120000 # Navigation timeout in milliseconds

    restart: always
