version: '3.8'

services:
  user-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-simulator-playwright:latest
    environment:
      - MIN_DELAY=2000            # Minimum delay in milliseconds
      - MAX_DELAY=10000           # Maximum delay in milliseconds
      - CONCURRENCY=5             # Number of concurrent sessions per script instance
      - TARGET_WEBSITE=https://www.example.com  # Replace with your target website
      - DISABLE_IMAGES=true       # Disable images to reduce resource usage
      - DISABLE_CSS=true          # Disable CSS to reduce resource usage
      - VIEWPORT_WIDTH=1024       # Width of the browser viewport
      - VIEWPORT_HEIGHT=768       # Height of the browser viewport
      - PM2_INSTANCES=5           # Number of script instances to run
      - ONLY_INTERNAL_LINKS=true  # Set to 'true' to only follow internal links
      - DEBUG=false               # Set to 'true' to enable debug logging
    env_file:
      - .env  # If you are using an .env file
    restart: always
